#!/usr/bin/env python3
"""
LucidLink Connect MCP Server for Claude Desktop
Provides access to LucidLink Connect API: filesystem entries, external data stores,
and external entries (bring-your-own-bucket).
"""

import json
import time
import os
import sys
import re
import logging
import subprocess
import asyncio
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from enum import Enum

import docker
import requests
import keyring
from mcp.server import Server
from mcp.types import Tool, TextContent, Resource
from mcp.server.stdio import stdio_server

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Constants
API_BASE_URL = "http://localhost:3003/api/v1"
CONTAINER_NAME = "lucidlink-api"
CONTAINER_IMAGE = "lucidlink/lucidlink-api:latest"
DOCKER_TIMEOUT = 60  # seconds
RATE_LIMIT_CALLS = 10
RATE_LIMIT_WINDOW = 60  # seconds

CONNECT_WORKFLOW_GUIDE = """LucidLink Connect MCP Server — Workflow Guide
=============================================

WHAT IS LUCIDLINK CONNECT?
LucidLink Connect links existing S3 objects into a filespace as read-only "external entries"
without copying data. S3 credentials need only s3:GetObject permission.

TWO-PART SYSTEM:
• Data Stores — S3 bucket connection credentials (stored per-filespace, encrypted)
• External Entries — filespace metadata records pointing to individual S3 objects

QUICKSTART (3 steps):
  Step 1: Create a data store
    tool: create_data_store
    required: filespace_id, name, access_key, secret_key, bucket_name, use_virtual_addressing

  Step 2: Ensure folder structure exists (use high-level tool)
    tool: ensure_folder_path
    required: filespace_id, path (e.g. "/videos/2024")

  Step 3: Link S3 objects
    tool: import_s3_object (one at a time)
      OR
    tool: bulk_import_s3_objects (many at once)

HIGH-LEVEL WORKFLOW TOOLS (recommended):
  • ensure_folder_path   — creates /a/b/c directory hierarchy in one call
  • import_s3_object     — ensures dirs + links one S3 object
  • bulk_import_s3_objects — ensures dirs + links many objects, reports results
  • generate_connect_ui  — generates a browser-based import UI (no Claude needed)

PRIMITIVE API TOOLS (for fine-grained control):
  Entries:         create_entry, resolve_entry, get_entry, delete_entry, list_entry_children
  Data Stores:     create_data_store, list_data_stores, get_data_store, update_data_store, delete_data_store
  External Entries: create_external_entry, list_external_entry_ids, delete_external_entry

EXAMPLE PAYLOADS:
  create_data_store body:
    { "name": "my-bucket", "kind": "S3DataStore",
      "s3StorageParams": { "bucketName": "my-bucket", "accessKey": "AKI...", "secretKey": "...",
                           "region": "us-east-1", "useVirtualAddressing": true,
                           "urlExpirationMinutes": 10080 } }

  create_external_entry body:
    { "path": "/media/clip.mp4", "kind": "SingleObjectFile",
      "dataStoreId": "<ds-id>",
      "singleObjectFileParams": { "objectId": "media/clip.mp4" } }

LIMITATIONS:
  • Read-only (external entries cannot be written to)
  • Individual object linking (no bucket-level mount)
  • S3 only (other clouds planned)
  • No TeamCache support
  • Delete removes filespace entry only (not S3 object)
  • Copy creates a native LucidLink file (no longer external)

ROTATING CREDENTIALS:
  Use update_data_store with new access_key + secret_key (PATCH endpoint)

COMMON ERRORS:
  409 on create_entry → folder already exists, use resolve_entry to get its ID
  404 on resolve_entry → path doesn't exist, use create_entry on parent
  401 → bearer token expired, re-run initialize_api
"""

CONNECT_UI_TEMPLATE = """<!-- Generated by LucidLink Connect MCP Server -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>LucidLink Connect</title>
<style>
:root {
  --blue: #0047FF; --blue-dark: #0038cc; --blue-dim: #e8eeff;
  --bg: #F0F4FF; --surface: #fff; --border: #dde3f0;
  --text: #0a0f1e; --muted: #6b7280;
  --ok: #059669; --ok-bg: #d1fae5;
  --err: #dc2626; --err-bg: #fee2e2;
  --r: 12px;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; padding: 32px 20px; font-size: 14px; line-height: 1.5; }
.app { max-width: 700px; margin: 0 auto; }
.header { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 28px; }
.logo { width: 36px; height: 36px; background: var(--blue); border-radius: 8px; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.header h1 { font-size: 20px; font-weight: 700; color: var(--blue); line-height: 1.2; }
.header p { font-size: 13px; color: var(--muted); margin-top: 2px; }
.step { background: var(--surface); border: 1px solid var(--border); border-radius: var(--r); margin-bottom: 10px; overflow: hidden; transition: opacity 0.2s; }
.step.locked { opacity: 0.45; pointer-events: none; }
.step-head { display: flex; align-items: center; gap: 10px; padding: 15px 18px; }
.num { width: 24px; height: 24px; border-radius: 50%; background: var(--blue-dim); color: var(--blue); font-size: 12px; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.step.done .num { background: var(--blue); color: #fff; }
.step-title { font-weight: 600; font-size: 14px; }
.step-tag { margin-left: auto; font-size: 11px; font-weight: 600; color: var(--ok); background: var(--ok-bg); padding: 2px 9px; border-radius: 20px; display: none; }
.step.done .step-tag { display: inline-block; }
.step-body { padding: 0 18px 18px; }
.field { margin-bottom: 12px; }
label { display: block; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: var(--muted); margin-bottom: 4px; }
input, select, textarea { width: 100%; padding: 8px 11px; border: 1px solid var(--border); border-radius: 8px; font: inherit; font-size: 13px; background: #fafbff; color: var(--text); outline: none; transition: border-color 0.15s; }
input:focus, select:focus, textarea:focus { border-color: var(--blue); background: #fff; }
textarea { resize: vertical; min-height: 110px; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 12px; }
.g2 { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
.g3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; }
.check { display: flex; align-items: center; gap: 7px; }
.check input[type=checkbox] { width: 14px; height: 14px; accent-color: var(--blue); flex-shrink: 0; cursor: pointer; }
.check label { text-transform: none; letter-spacing: 0; font-size: 13px; font-weight: 500; color: var(--text); margin: 0; }
.btn { display: inline-flex; align-items: center; gap: 5px; padding: 8px 18px; border-radius: 8px; font: inherit; font-size: 13px; font-weight: 600; cursor: pointer; border: none; transition: background 0.15s, transform 0.1s; }
.btn:active:not(:disabled) { transform: scale(0.98); }
.btn-p { background: var(--blue); color: #fff; }
.btn-p:hover:not(:disabled) { background: var(--blue-dark); }
.btn-p:disabled { background: #93b4ff; cursor: not-allowed; }
.btn-sm { padding: 6px 13px; font-size: 12px; }
.alert { display: flex; align-items: center; gap: 7px; padding: 9px 12px; border-radius: 8px; font-size: 13px; font-weight: 500; margin-top: 10px; }
.alert-ok { background: var(--ok-bg); color: #065f46; }
.alert-err { background: var(--err-bg); color: #991b1b; }
.dot { width: 6px; height: 6px; border-radius: 50%; background: currentColor; flex-shrink: 0; }
.ds-grid { display: flex; flex-direction: column; gap: 7px; margin-bottom: 14px; }
.ds-card { border: 2px solid var(--border); border-radius: 8px; padding: 11px 13px; cursor: pointer; display: flex; align-items: center; gap: 11px; transition: border-color 0.15s, background 0.15s; }
.ds-card:hover { border-color: #93b4ff; background: #fafbff; }
.ds-card.sel { border-color: var(--blue); background: var(--blue-dim); }
.ds-radio { width: 16px; height: 16px; border: 2px solid var(--border); border-radius: 50%; flex-shrink: 0; display: flex; align-items: center; justify-content: center; transition: border-color 0.15s; }
.ds-card.sel .ds-radio { border-color: var(--blue); }
.ds-dot { width: 7px; height: 7px; border-radius: 50%; background: var(--blue); display: none; }
.ds-card.sel .ds-dot { display: block; }
.ds-name { font-weight: 600; font-size: 13px; }
.ds-meta { color: var(--muted); font-size: 12px; margin-top: 1px; }
.ds-empty { color: var(--muted); font-size: 13px; padding: 16px 0; }
.disc-btn { display: flex; align-items: center; gap: 6px; background: none; border: none; color: var(--blue); font: inherit; font-size: 13px; font-weight: 600; cursor: pointer; padding: 8px 0; }
.disc-btn .arrow { display: inline-block; transition: transform 0.2s; }
.disc-btn.open .arrow { transform: rotate(90deg); }
.disc-body { background: #f8faff; border: 1px solid var(--border); border-radius: 8px; padding: 15px; margin-top: 8px; display: none; }
.disc-body.open { display: block; }
table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 14px; }
th { background: var(--bg); color: var(--blue); text-align: left; padding: 7px 9px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.06em; border-bottom: 2px solid var(--border); }
td { padding: 7px 9px; border-bottom: 1px solid #f3f4f6; word-break: break-all; }
tr:last-child td { border-bottom: none; }
.badge { display: inline-block; padding: 1px 7px; border-radius: 9px; font-size: 10px; font-weight: 700; }
.b-ok { background: var(--ok-bg); color: #065f46; }
.b-err { background: var(--err-bg); color: #991b1b; }
.summary { font-size: 13px; font-weight: 600; margin-top: 12px; }
.muted { color: var(--muted); font-weight: 400; }
</style>
</head>
<body>
<div class="app">

  <div class="header">
    <div class="logo">
      <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
        <circle cx="10" cy="10" r="8" stroke="white" stroke-width="2"/>
        <circle cx="10" cy="10" r="3" fill="white"/>
      </svg>
    </div>
    <div>
      <h1>LucidLink Connect</h1>
      <p>Link S3 objects into a filespace as external entries</p>
    </div>
  </div>

  <!-- Step 1: Connect -->
  <div class="step" id="s1">
    <div class="step-head">
      <div class="num">1</div>
      <div class="step-title">Connect to API</div>
      <div class="step-tag" id="t1">Connected</div>
    </div>
    <div class="step-body">
      <div class="g2">
        <div class="field">
          <label>API Base URL</label>
          <input type="text" id="baseUrl" value="http://localhost:3003">
        </div>
        <div class="field">
          <label>Bearer Token</label>
          <input type="password" id="token" placeholder="Your bearer token">
        </div>
      </div>
      <button class="btn btn-p" id="connectBtn" onclick="doConnect()">Connect</button>
      <div id="s1msg"></div>
    </div>
  </div>

  <!-- Step 2: Select Filespace -->
  <div class="step locked" id="s2">
    <div class="step-head">
      <div class="num">2</div>
      <div class="step-title">Select Filespace</div>
      <div class="step-tag" id="t2">—</div>
    </div>
    <div class="step-body">
      <div class="field">
        <label>Filespace</label>
        <select id="fsSelect" onchange="onFsChange()">
          <option value="">— choose a filespace —</option>
        </select>
      </div>
    </div>
  </div>

  <!-- Step 3: Data Store -->
  <div class="step locked" id="s3">
    <div class="step-head">
      <div class="num">3</div>
      <div class="step-title">Data Store</div>
      <div class="step-tag" id="t3">—</div>
    </div>
    <div class="step-body">
      <div id="dsLoading" style="font-size:13px;color:var(--muted)">Loading…</div>
      <div id="dsContent" style="display:none">
        <div class="ds-grid" id="dsGrid"></div>
        <button class="disc-btn" id="createBtn" onclick="toggleCreate()">
          <span class="arrow">&#9658;</span> Create new data store
        </button>
        <div class="disc-body" id="createBody">
          <div class="g2" style="margin-bottom:10px">
            <div class="field">
              <label>Store name</label>
              <input type="text" id="dsName" placeholder="e.g. production-media">
            </div>
            <div class="field">
              <label>S3 bucket name</label>
              <input type="text" id="dsBucket" placeholder="my-bucket">
            </div>
          </div>
          <div class="g3" style="margin-bottom:10px">
            <div class="field">
              <label>Region</label>
              <input type="text" id="dsRegion" value="us-east-1">
            </div>
            <div class="field">
              <label>Access Key ID</label>
              <input type="text" id="dsAK" placeholder="AKIA…">
            </div>
            <div class="field">
              <label>Secret Access Key</label>
              <input type="password" id="dsSK" placeholder="••••••••">
            </div>
          </div>
          <div class="check" style="margin-bottom:12px">
            <input type="checkbox" id="dsVA" checked>
            <label for="dsVA">Virtual-hosted addressing (recommended for AWS S3)</label>
          </div>
          <div id="createErr" style="display:none" class="alert alert-err"></div>
          <button class="btn btn-p btn-sm" onclick="doCreate()">Create Data Store</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Step 4: Import -->
  <div class="step locked" id="s4">
    <div class="step-head">
      <div class="num">4</div>
      <div class="step-title">Import S3 Objects</div>
    </div>
    <div class="step-body">
      <div class="field">
        <label>S3 Object Keys — one per line</label>
        <textarea id="keys" placeholder="media/videos/clip1.mp4&#10;media/videos/clip2.mp4&#10;docs/readme.txt"></textarea>
      </div>
      <div class="field">
        <label>LucidLink path prefix</label>
        <input type="text" id="prefix" value="/" placeholder="/ or /imports/2024">
      </div>
      <div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">
        <button class="btn btn-p" id="importBtn" onclick="doImport()">Import Objects</button>
        <span id="importMsg" style="font-size:13px;color:var(--muted)"></span>
      </div>
      <div id="resultsWrap" style="display:none">
        <table>
          <thead><tr><th>S3 Key</th><th>LucidLink Path</th><th>Status</th><th>Detail</th></tr></thead>
          <tbody id="resultsBody"></tbody>
        </table>
        <div class="summary" id="summary"></div>
      </div>
    </div>
  </div>

</div>
<script>
const sleep = ms => new Promise(r => setTimeout(r, ms));
const h = s => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');

const ST = { fsId: '{FILESPACE_ID}', dsId: '{DATA_STORE_ID}', filespaces: [], datastores: [] };

function base() { return document.getElementById('baseUrl').value.trim().replace(/\\/+$/, ''); }
function hdrs() { return { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + document.getElementById('token').value.trim() }; }
function unlock(id) { document.getElementById(id).classList.remove('locked'); }
function done(sid, tid, label) {
  document.getElementById(sid).classList.add('done');
  const t = document.getElementById(tid); t.textContent = label; t.style.display = 'inline-block';
}
function showAlert(id, type, msg) {
  const el = document.getElementById(id);
  el.className = 'alert alert-' + type;
  el.innerHTML = '<span class="dot"></span>' + h(msg);
  el.style.display = 'flex';
}
function hideAlert(id) { document.getElementById(id).style.display = 'none'; }

async function doConnect() {
  const btn = document.getElementById('connectBtn');
  btn.disabled = true; btn.textContent = 'Connecting…';
  hideAlert('s1msg');
  try {
    const r = await fetch(base() + '/api/v1/filespaces', { headers: hdrs() });
    if (!r.ok) throw new Error('API returned ' + r.status + '. Check your token and URL.');
    const d = await r.json();
    ST.filespaces = Array.isArray(d) ? d : (Array.isArray(d.data) ? d.data : []);
    const sel = document.getElementById('fsSelect');
    sel.innerHTML = '<option value="">— choose a filespace —</option>';
    ST.filespaces.forEach(fs => {
      const o = document.createElement('option');
      o.value = fs.id; o.textContent = fs.name || fs.id;
      if (fs.id === ST.fsId) o.selected = true;
      sel.appendChild(o);
    });
    const n = ST.filespaces.length;
    showAlert('s1msg', 'ok', 'Connected · ' + n + ' filespace' + (n !== 1 ? 's' : '') + ' found');
    done('s1', 't1', 'Connected');
    unlock('s2');
    if (ST.fsId && ST.filespaces.find(f => f.id === ST.fsId)) await onFsChange();
  } catch(e) {
    showAlert('s1msg', 'err', e.message || 'Connection failed');
  }
  btn.disabled = false; btn.textContent = 'Connect';
}

async function onFsChange() {
  const sel = document.getElementById('fsSelect');
  const id = sel.value; if (!id) return;
  ST.fsId = id; ST.dsId = '';
  done('s2', 't2', sel.options[sel.selectedIndex].text);
  document.getElementById('s4').classList.add('locked');
  unlock('s3');
  await loadDs();
}

async function loadDs() {
  document.getElementById('dsLoading').style.display = '';
  document.getElementById('dsContent').style.display = 'none';
  try {
    const r = await fetch(base() + '/api/v1/filespaces/' + ST.fsId + '/external/data-stores', { headers: hdrs() });
    if (!r.ok) throw new Error('HTTP ' + r.status);
    const d = await r.json();
    ST.datastores = Array.isArray(d) ? d : (Array.isArray(d.data) ? d.data : []);
    renderDs();
    document.getElementById('dsLoading').style.display = 'none';
    document.getElementById('dsContent').style.display = '';
    if (ST.dsId && ST.datastores.find(ds => ds.id === ST.dsId)) selectDs(ST.dsId);
  } catch(e) {
    document.getElementById('dsLoading').textContent = 'Error loading data stores: ' + e.message;
  }
}

function renderDs() {
  const g = document.getElementById('dsGrid');
  if (!ST.datastores.length) {
    g.innerHTML = '<div class="ds-empty">No data stores yet — create one below.</div>';
    return;
  }
  g.innerHTML = ST.datastores.map(ds => {
    const p = ds.s3StorageParams || {};
    const meta = [p.bucketName, p.region].filter(Boolean).join(' · ');
    return '<div class="ds-card" id="dsc-' + ds.id + '" onclick="selectDs(\'' + ds.id + '\')">' +
      '<div class="ds-radio"><div class="ds-dot"></div></div>' +
      '<div style="flex:1;min-width:0">' +
      '<div class="ds-name">' + h(ds.name) + '</div>' +
      '<div class="ds-meta">' + h(meta || 'S3DataStore') + '</div>' +
      '</div></div>';
  }).join('');
}

function selectDs(id) {
  ST.dsId = id;
  document.querySelectorAll('.ds-card').forEach(c => c.classList.remove('sel'));
  const card = document.getElementById('dsc-' + id);
  if (card) card.classList.add('sel');
  const ds = ST.datastores.find(d => d.id === id);
  done('s3', 't3', ds ? ds.name : 'Selected');
  unlock('s4');
}

function toggleCreate() {
  document.getElementById('createBtn').classList.toggle('open');
  document.getElementById('createBody').classList.toggle('open');
}

async function doCreate() {
  const name = document.getElementById('dsName').value.trim();
  const bucket = document.getElementById('dsBucket').value.trim();
  const region = document.getElementById('dsRegion').value.trim() || 'us-east-1';
  const ak = document.getElementById('dsAK').value.trim();
  const sk = document.getElementById('dsSK').value.trim();
  const va = document.getElementById('dsVA').checked;
  hideAlert('createErr');
  if (!name || !bucket || !ak || !sk) {
    showAlert('createErr', 'err', 'Name, bucket, access key and secret key are required.');
    return;
  }
  const body = { name, kind: 'S3DataStore', s3StorageParams: {
    bucketName: bucket, accessKey: ak, secretKey: sk,
    region, useVirtualAddressing: va, urlExpirationMinutes: 10080
  }};
  try {
    const r = await fetch(base() + '/api/v1/filespaces/' + ST.fsId + '/external/data-stores',
      { method: 'POST', headers: hdrs(), body: JSON.stringify(body) });
    const d = await r.json().catch(() => null);
    if (!r.ok) { showAlert('createErr', 'err', (d && (d.message || d.error)) || 'HTTP ' + r.status); return; }
    const newDs = (d && d.data) ? d.data : d;
    if (newDs && newDs.id) {
      ST.datastores.push(newDs);
      renderDs();
      toggleCreate();
      ['dsName','dsBucket','dsAK','dsSK'].forEach(i => document.getElementById(i).value = '');
      document.getElementById('dsRegion').value = 'us-east-1';
      document.getElementById('dsVA').checked = true;
      selectDs(newDs.id);
    }
  } catch(e) { showAlert('createErr', 'err', e.message || 'Failed to create data store'); }
}

async function resolveEntry(path) {
  const r = await fetch(base() + '/api/v1/filespaces/' + ST.fsId + '/entries/resolve?path=' + encodeURIComponent(path), { headers: hdrs() });
  return { ok: r.status === 200, status: r.status, data: r.ok ? await r.json() : null };
}
async function createEntry(parentId, name) {
  const r = await fetch(base() + '/api/v1/filespaces/' + ST.fsId + '/entries',
    { method: 'POST', headers: hdrs(), body: JSON.stringify({ parentId, name, type: 'dir' }) });
  const data = r.status < 300 ? await r.json() : null;
  return { ok: r.status === 201, status: r.status, data };
}
async function ensurePath(path) {
  const parts = path.replace(/^\\/+|\\/+$/g, '').split('/').filter(Boolean);
  if (!parts.length) return { ok: true };
  let cur = '', curId = null;
  for (const name of parts) {
    cur += '/' + name;
    let ok = false;
    for (let i = 0; i < 3; i++) {
      const res = await resolveEntry(cur);
      if (res.ok) {
        curId = (res.data && res.data.data) ? res.data.data.id : (res.data ? res.data.id : null);
        ok = true; break;
      }
      const cr = await createEntry(curId, name);
      if (cr.ok) {
        curId = (cr.data && cr.data.data) ? cr.data.data.id : (cr.data ? cr.data.id : null);
        ok = true; break;
      }
      if (cr.status === 409) { await sleep(200); continue; }
      await sleep(500);
    }
    if (!ok) return { ok: false, error: 'Could not create \'' + cur + '\'' };
  }
  return { ok: true };
}

async function doImport() {
  const raw = document.getElementById('keys').value.trim();
  const prefix = document.getElementById('prefix').value.trim().replace(/\\/+$/, '') || '';
  const msg = document.getElementById('importMsg');
  const btn = document.getElementById('importBtn');
  if (!raw) { msg.textContent = 'Enter at least one S3 key.'; return; }

  const keys = raw.split('
').map(k => k.trim()).filter(Boolean);
  const objects = keys.map(k => ({ s3Key: k, llPath: prefix + '/' + k.replace(/^\\/+/, '') }));

  btn.disabled = true;
  document.getElementById('resultsBody').innerHTML = '';
  document.getElementById('resultsWrap').style.display = '';
  document.getElementById('summary').textContent = '';

  const dirs = new Set();
  objects.forEach(({ llPath }) => {
    const parts = llPath.replace(/^\\/+/, '').split('/'); parts.pop();
    if (parts.length && parts[0]) dirs.add('/' + parts.join('/'));
  });

  let di = 0;
  const sortedDirs = Array.from(dirs).sort();
  for (const dir of sortedDirs) {
    msg.textContent = 'Creating directories… (' + (++di) + '/' + sortedDirs.length + ')';
    const res = await ensurePath(dir);
    if (!res.ok) { msg.textContent = 'Error: ' + res.error; btn.disabled = false; return; }
  }

  let ok = 0, fail = 0;
  const tbody = document.getElementById('resultsBody');
  for (let i = 0; i < objects.length; i++) {
    const { s3Key, llPath } = objects[i];
    msg.textContent = 'Importing ' + (i + 1) + ' / ' + objects.length + '…';
    const r = await fetch(base() + '/api/v1/filespaces/' + ST.fsId + '/external/entries', {
      method: 'POST', headers: hdrs(),
      body: JSON.stringify({ path: llPath, kind: 'SingleObjectFile', dataStoreId: ST.dsId, singleObjectFileParams: { objectId: s3Key } })
    });
    let rd = null; try { rd = await r.json(); } catch(_e) {}
    const tr = document.createElement('tr');
    if (r.ok) {
      ok++;
      const eid = (rd && rd.data) ? rd.data.id : (rd ? rd.id : '');
      tr.innerHTML = '<td>' + h(s3Key) + '</td><td>' + h(llPath) + '</td><td><span class="badge b-ok">OK</span></td><td style="color:var(--muted);font-size:11px">' + h(eid || '') + '</td>';
    } else {
      fail++;
      const em = (rd && (rd.message || rd.error)) || 'HTTP ' + r.status;
      tr.innerHTML = '<td>' + h(s3Key) + '</td><td>' + h(llPath) + '</td><td><span class="badge b-err">Error</span></td><td style="color:var(--err);font-size:11px">' + h(em) + '</td>';
    }
    tbody.appendChild(tr);
  }
  msg.textContent = '';
  const total = objects.length;
  document.getElementById('summary').innerHTML = ok === total
    ? 'All ' + ok + ' object' + (ok !== 1 ? 's' : '') + ' imported successfully.'
    : ok + ' of ' + total + ' imported. <span class="muted">' + fail + ' failed.</span>';
  btn.disabled = false;
}

window.addEventListener('DOMContentLoaded', function() {
  const p = new URLSearchParams(location.search);
  if (p.get('token')) document.getElementById('token').value = p.get('token');
  if (p.get('url')) document.getElementById('baseUrl').value = p.get('url');
});
</script>
</body>
</html>"""


@dataclass
class ApiResponse:
    """Standardized API response"""
    success: bool
    data: Optional[Dict] = None
    error: Optional[str] = None
    status_code: Optional[int] = None


class RateLimiter:
    """Sliding-window rate limiter"""
    def __init__(self, max_calls: int = RATE_LIMIT_CALLS, window: int = RATE_LIMIT_WINDOW):
        self.max_calls = max_calls
        self.window = window
        self.calls = []

    def check_limit(self) -> bool:
        now = time.time()
        self.calls = [t for t in self.calls if now - t < self.window]
        if len(self.calls) >= self.max_calls:
            return False
        self.calls.append(now)
        return True

    def time_until_reset(self) -> int:
        if not self.calls:
            return 0
        return max(0, int(self.window - (time.time() - self.calls[0])))


class DockerManager:
    """Manages Docker Desktop and LucidLink container"""

    def __init__(self):
        self.client = None

    def is_docker_installed(self) -> bool:
        return os.path.exists('/Applications/Docker.app')

    def is_docker_running(self) -> bool:
        try:
            self.client = docker.from_env()
            self.client.ping()
            return True
        except Exception as e:
            logger.debug(f"Docker not running: {e}")
            return False

    def start_docker(self) -> bool:
        if not self.is_docker_installed():
            return False
        if self.is_docker_running():
            return True
        try:
            logger.info("Starting Docker Desktop...")
            subprocess.run(['open', '-a', 'Docker'], check=True)
            for i in range(DOCKER_TIMEOUT):
                if self.is_docker_running():
                    logger.info("Docker Desktop started successfully")
                    return True
                time.sleep(1)
            logger.error("Docker Desktop failed to start within timeout")
            return False
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to start Docker Desktop: {e}")
            return False

    def image_exists(self, image_name: str) -> bool:
        if not self.is_docker_running():
            if not self.start_docker():
                return False
        try:
            self.client.images.get(image_name)
            return True
        except docker.errors.ImageNotFound:
            return False
        except Exception as e:
            logger.error(f"Error checking for image: {e}")
            return False

    def pull_image(self, image_name: str) -> tuple[bool, str]:
        if not self.is_docker_running():
            if not self.start_docker():
                return False, "Docker is not running and failed to start"
        try:
            logger.info(f"Pulling image {image_name} from Docker Hub...")
            self.client.images.pull(image_name)
            return True, f"Successfully pulled image: {image_name}"
        except docker.errors.APIError as e:
            logger.error(f"Failed to pull image: {e}")
            return False, f"Failed to pull image from Docker Hub: {str(e)}"
        except Exception as e:
            logger.error(f"Unexpected error pulling image: {e}")
            return False, f"Unexpected error: {str(e)}"

    def ensure_container_running(self, image_name: str = CONTAINER_IMAGE,
                                 container_name: str = CONTAINER_NAME) -> tuple[Optional[docker.models.containers.Container], Optional[str]]:
        if not self.is_docker_running():
            if not self.start_docker():
                return None, "Docker Desktop is not running and failed to start"
        try:
            container = self.client.containers.get(container_name)
            if container.status != 'running':
                logger.info(f"Starting existing container {container_name}")
                container.start()
                time.sleep(2)
            return container, None
        except docker.errors.NotFound:
            if not self.image_exists(image_name):
                logger.info(f"Image {image_name} not found locally, attempting to pull...")
                success, message = self.pull_image(image_name)
                if not success:
                    return None, (
                        f"Container image '{image_name}' not found locally and failed to pull. "
                        f"Error: {message}"
                    )
            try:
                container = self.client.containers.run(
                    image_name,
                    detach=True,
                    name=container_name,
                    ports={'3003/tcp': 3003},
                    restart_policy={"Name": "unless-stopped"}
                )
                time.sleep(3)
                return container, None
            except docker.errors.APIError as e:
                logger.error(f"Failed to create container: {e}")
                return None, f"Failed to create container: {str(e)}"
        except Exception as e:
            return None, f"Unexpected error: {str(e)}"

    def get_container_logs(self, lines: int = 50) -> str:
        try:
            container = self.client.containers.get(CONTAINER_NAME)
            return container.logs(tail=lines, decode=True)
        except Exception as e:
            return f"Error getting logs: {e}"

    def stop_container(self) -> bool:
        try:
            container = self.client.containers.get(CONTAINER_NAME)
            container.stop()
            return True
        except Exception:
            return False


class LucidLinkAPIClient:
    """Client for LucidLink Connect API operations"""

    def __init__(self, bearer_token: str, base_url: str = API_BASE_URL):
        self.base_url = base_url
        self.bearer_token = bearer_token
        self.headers = {
            "Authorization": f"Bearer {bearer_token}",
            "Content-Type": "application/json"
        }
        self.rate_limiter = RateLimiter()

    def _make_request(self, method: str, endpoint: str,
                      data: Optional[Dict] = None,
                      params: Optional[Dict] = None) -> ApiResponse:
        if not self.rate_limiter.check_limit():
            wait_time = self.rate_limiter.time_until_reset()
            return ApiResponse(
                success=False,
                error=f"Rate limit exceeded. Please wait {wait_time} seconds."
            )
        url = f"{self.base_url}{endpoint}"
        try:
            response = requests.request(
                method=method,
                url=url,
                headers=self.headers,
                json=data,
                params=params,
                timeout=30
            )
            if response.status_code in [200, 201, 204]:
                try:
                    response_data = response.json() if response.text else {}
                except json.JSONDecodeError:
                    response_data = {}
                return ApiResponse(success=True, data=response_data, status_code=response.status_code)
            else:
                error_msg = self._parse_error_response(response)
                return ApiResponse(success=False, error=error_msg, status_code=response.status_code)
        except requests.exceptions.ConnectionError:
            return ApiResponse(success=False, error="Cannot connect to API. Please ensure Docker container is running.")
        except requests.exceptions.Timeout:
            return ApiResponse(success=False, error="API request timed out.")
        except Exception as e:
            return ApiResponse(success=False, error=f"Unexpected error: {str(e)}")

    def _parse_error_response(self, response) -> str:
        try:
            error_data = response.json()
            if 'message' in error_data:
                return error_data['message']
            elif 'error' in error_data:
                return error_data['error']
        except:
            pass
        status_messages = {
            400: "Invalid request parameters",
            401: "Authentication failed - check your Bearer token",
            403: "Permission denied",
            404: "Resource not found",
            409: "Resource already exists",
            422: "Request cannot be processed",
            500: "API server error"
        }
        return status_messages.get(response.status_code, f"API error (status {response.status_code})")

    # Filesystem Entries
    def create_entry(self, filespace_id: str, parent_id: str, name: str) -> ApiResponse:
        """Create a directory entry in a filespace"""
        data = {"parentId": parent_id, "name": name, "type": "dir"}
        return self._make_request("POST", f"/filespaces/{filespace_id}/entries", data)

    def resolve_entry(self, filespace_id: str, path: str) -> ApiResponse:
        """Resolve a filesystem path to an entry"""
        return self._make_request("GET", f"/filespaces/{filespace_id}/entries/resolve", params={"path": path})

    def get_entry(self, filespace_id: str, entry_id: str) -> ApiResponse:
        """Get a filesystem entry by ID"""
        return self._make_request("GET", f"/filespaces/{filespace_id}/entries/{entry_id}")

    def delete_entry(self, filespace_id: str, entry_id: str) -> ApiResponse:
        """Delete a filesystem entry (must be empty directory)"""
        return self._make_request("DELETE", f"/filespaces/{filespace_id}/entries/{entry_id}")

    def list_entry_children(self, filespace_id: str, entry_id: str,
                             limit: Optional[int] = None, next_cursor: Optional[str] = None) -> ApiResponse:
        """List children of a directory entry"""
        params = {}
        if limit:
            params["limit"] = limit
        if next_cursor:
            params["nextCursor"] = next_cursor
        return self._make_request("GET", f"/filespaces/{filespace_id}/entries/{entry_id}/children",
                                  params=params or None)

    # External Data Stores
    def create_data_store(self, filespace_id: str, name: str, access_key: str,
                          secret_key: str, bucket_name: str, use_virtual_addressing: bool,
                          region: Optional[str] = None, endpoint: Optional[str] = None,
                          url_expiration_minutes: Optional[int] = None) -> ApiResponse:
        """Create an S3 external data store"""
        s3_params: Dict[str, Any] = {
            "accessKey": access_key,
            "secretKey": secret_key,
            "bucketName": bucket_name,
            "useVirtualAddressing": use_virtual_addressing,
        }
        if region:
            s3_params["region"] = region
        if endpoint:
            s3_params["endpoint"] = endpoint
        if url_expiration_minutes is not None:
            s3_params["urlExpirationMinutes"] = url_expiration_minutes
        data = {"name": name, "kind": "S3DataStore", "s3StorageParams": s3_params}
        return self._make_request("POST", f"/filespaces/{filespace_id}/external/data-stores", data)

    def list_data_stores(self, filespace_id: str, name: Optional[str] = None) -> ApiResponse:
        """List data stores for a filespace"""
        params = {}
        if name:
            params["name"] = name
        return self._make_request("GET", f"/filespaces/{filespace_id}/external/data-stores",
                                  params=params or None)

    def get_data_store(self, filespace_id: str, data_store_id: str) -> ApiResponse:
        """Get a specific data store by ID"""
        return self._make_request("GET", f"/filespaces/{filespace_id}/external/data-stores/{data_store_id}")

    def update_data_store(self, filespace_id: str, data_store_id: str,
                          access_key: str, secret_key: str) -> ApiResponse:
        """Update data store credentials"""
        data = {"s3StorageParams": {"accessKey": access_key, "secretKey": secret_key}}
        return self._make_request("PATCH", f"/filespaces/{filespace_id}/external/data-stores/{data_store_id}", data)

    def delete_data_store(self, filespace_id: str, data_store_id: str) -> ApiResponse:
        """Delete a data store"""
        return self._make_request("DELETE", f"/filespaces/{filespace_id}/external/data-stores/{data_store_id}")

    def ensure_folder_path(self, filespace_id: str, path: str) -> tuple[bool, Optional[str], str]:
        """Create all directories in path, returning (success, leaf_entry_id, error_message)"""
        parts = [p for p in path.strip("/").split("/") if p]
        current_path = ""
        current_id = None
        for folder in parts:
            current_path += f"/{folder}"
            success = False
            for attempt in range(3):
                result = self.resolve_entry(filespace_id, current_path)
                if result.success:
                    current_id = result.data.get("id") if result.data else None
                    if not current_id and isinstance(result.data, dict):
                        current_id = result.data.get("data", {}).get("id")
                    success = True
                    break
                create_result = self.create_entry(filespace_id, current_id, folder)
                if create_result.success:
                    current_id = create_result.data.get("id") if create_result.data else None
                    if not current_id and isinstance(create_result.data, dict):
                        current_id = create_result.data.get("data", {}).get("id")
                    success = True
                    break
                if create_result.status_code == 409:
                    time.sleep(0.2)
                    continue
                time.sleep(0.5)
            if not success:
                return False, None, f"Failed to create/resolve '{current_path}'"
        return True, current_id, ""

    # External Entries
    def create_external_entry(self, filespace_id: str, path: str,
                               data_store_id: str, object_id: str) -> ApiResponse:
        """Create an external entry backed by an S3 object"""
        data = {
            "path": path,
            "kind": "SingleObjectFile",
            "dataStoreId": data_store_id,
            "singleObjectFileParams": {"objectId": object_id},
        }
        return self._make_request("POST", f"/filespaces/{filespace_id}/external/entries", data)

    def list_external_entry_ids(self, filespace_id: str, data_store_id: str,
                                 limit: Optional[int] = None, next_cursor: Optional[str] = None) -> ApiResponse:
        """List external entry IDs for a data store"""
        params: Dict[str, Any] = {"dataStoreId": data_store_id}
        if limit:
            params["limit"] = limit
        if next_cursor:
            params["nextCursor"] = next_cursor
        return self._make_request("GET", f"/filespaces/{filespace_id}/external/entries/ids", params=params)

    def delete_external_entry(self, filespace_id: str, entry_id: str) -> ApiResponse:
        """Delete an external entry"""
        return self._make_request("DELETE", f"/filespaces/{filespace_id}/external/entries/{entry_id}")

    def get_service_health(self) -> ApiResponse:
        """Check API service health"""
        return self._make_request("GET", "/health")


# Initialize MCP Server
server = Server("lucidlink-connect-api")

# Global instances
docker_mgr = DockerManager()
api_client: Optional[LucidLinkAPIClient] = None


def get_bearer_token() -> Optional[str]:
    """Get bearer token from environment or keychain"""
    token = os.getenv("LUCIDLINK_BEARER_TOKEN")
    if token:
        return token
    try:
        token = keyring.get_password("lucidlink-mcp", "bearer_token")
        if token:
            return token
    except Exception as e:
        logger.warning(f"Could not access keychain: {e}")
    return None


def format_success_message(operation: str, details: Dict) -> str:
    message = f"✅ {operation} completed successfully!\n\n"
    if details:
        message += "📋 Details:\n"
        message += json.dumps(details, indent=2, default=str)
    return message


def format_error_message(operation: str, error: str) -> str:
    user_friendly_errors = {
        "401": "Your authentication token is invalid or expired. Please update it in settings.",
        "404": "The requested resource was not found.",
        "409": "This resource already exists. Please choose a different name.",
        "ConnectionError": "Cannot connect to the API. Please ensure Docker Desktop is running.",
        "rate_limit": "Too many requests. Please wait a moment and try again."
    }
    for key, friendly_msg in user_friendly_errors.items():
        if key in str(error):
            error = friendly_msg
            break
    return f"❌ {operation} failed\n\n{error}\n\n💡 Tip: Check that Docker is running and your token is valid."


# MCP Server Tool Definitions
@server.list_tools()
async def list_tools():
    """List all available tools"""
    return [
        # Docker Management
        Tool(
            name="check_docker_status",
            description="Check if Docker Desktop is running and start it if needed",
            inputSchema={"type": "object", "properties": {}}
        ),
        Tool(
            name="start_api_container",
            description="Start the LucidLink API container",
            inputSchema={"type": "object", "properties": {}}
        ),
        Tool(
            name="stop_api_container",
            description="Stop the LucidLink API container",
            inputSchema={"type": "object", "properties": {}}
        ),
        Tool(
            name="view_container_logs",
            description="View recent logs from the API container",
            inputSchema={
                "type": "object",
                "properties": {
                    "lines": {
                        "type": "integer",
                        "description": "Number of log lines to retrieve"
                    }
                }
            }
        ),
        Tool(
            name="pull_container_image",
            description="Pull the LucidLink API image from Docker Hub",
            inputSchema={"type": "object", "properties": {}}
        ),
        Tool(
            name="check_container_image",
            description="Check if the LucidLink API image is available locally",
            inputSchema={"type": "object", "properties": {}}
        ),

        # Filesystem Entries
        Tool(
            name="create_entry",
            description="Create a new directory inside a filespace",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "parent_id": {
                        "type": "string",
                        "description": "Parent directory entry ID"
                    },
                    "name": {
                        "type": "string",
                        "description": "New directory name"
                    }
                },
                "required": ["filespace_id", "parent_id", "name"]
            }
        ),
        Tool(
            name="resolve_entry",
            description="Look up a filesystem entry by path",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "path": {
                        "type": "string",
                        "description": "Full filesystem path (e.g. /reports/q3/)"
                    }
                },
                "required": ["filespace_id", "path"]
            }
        ),
        Tool(
            name="get_entry",
            description="Get details about a filesystem entry by ID",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "entry_id": {
                        "type": "string",
                        "description": "Filesystem entry ID"
                    }
                },
                "required": ["filespace_id", "entry_id"]
            }
        ),
        Tool(
            name="delete_entry",
            description="Delete a filesystem entry (directory must be empty)",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "entry_id": {
                        "type": "string",
                        "description": "Entry ID to delete"
                    },
                    "confirm": {
                        "type": "boolean",
                        "description": "Must be true to proceed"
                    }
                },
                "required": ["filespace_id", "entry_id", "confirm"]
            }
        ),
        Tool(
            name="list_entry_children",
            description="List the contents of a directory in a filespace",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "entry_id": {
                        "type": "string",
                        "description": "Directory entry ID to list"
                    },
                    "limit": {
                        "type": "integer",
                        "description": "Max entries to return"
                    },
                    "next_cursor": {
                        "type": "string",
                        "description": "Pagination cursor from previous response"
                    }
                },
                "required": ["filespace_id", "entry_id"]
            }
        ),

        # External Data Stores
        Tool(
            name="create_data_store",
            description="Create an S3 external data store for a filespace",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "name": {
                        "type": "string",
                        "description": "Data store name"
                    },
                    "access_key": {
                        "type": "string",
                        "description": "S3 access key ID"
                    },
                    "secret_key": {
                        "type": "string",
                        "description": "S3 secret access key"
                    },
                    "bucket_name": {
                        "type": "string",
                        "description": "S3 bucket name"
                    },
                    "use_virtual_addressing": {
                        "type": "boolean",
                        "description": "Use virtual-hosted–style addressing (true for AWS S3)"
                    },
                    "region": {
                        "type": "string",
                        "description": "AWS region (provide region or endpoint)"
                    },
                    "endpoint": {
                        "type": "string",
                        "description": "Custom S3-compatible endpoint URL"
                    },
                    "url_expiration_minutes": {
                        "type": "integer",
                        "description": "Pre-signed URL expiration in minutes"
                    }
                },
                "required": ["filespace_id", "name", "access_key", "secret_key", "bucket_name", "use_virtual_addressing"]
            }
        ),
        Tool(
            name="list_data_stores",
            description="List external data stores configured for a filespace",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "name": {
                        "type": "string",
                        "description": "Filter by data store name"
                    }
                },
                "required": ["filespace_id"]
            }
        ),
        Tool(
            name="get_data_store",
            description="Get details about a specific external data store",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID"
                    }
                },
                "required": ["filespace_id", "data_store_id"]
            }
        ),
        Tool(
            name="update_data_store",
            description="Update credentials for an external data store",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID"
                    },
                    "access_key": {
                        "type": "string",
                        "description": "New S3 access key ID"
                    },
                    "secret_key": {
                        "type": "string",
                        "description": "New S3 secret access key"
                    }
                },
                "required": ["filespace_id", "data_store_id", "access_key", "secret_key"]
            }
        ),
        Tool(
            name="delete_data_store",
            description="Delete an external data store from a filespace",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID to delete"
                    },
                    "confirm": {
                        "type": "boolean",
                        "description": "Must be true to proceed"
                    }
                },
                "required": ["filespace_id", "data_store_id", "confirm"]
            }
        ),

        # External Entries
        Tool(
            name="create_external_entry",
            description="Create an external file entry backed by an object in a data store",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "path": {
                        "type": "string",
                        "description": "Filesystem path for the entry (e.g. /videos/clip.mp4)"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID containing the object"
                    },
                    "object_id": {
                        "type": "string",
                        "description": "Object key/ID within the bucket"
                    }
                },
                "required": ["filespace_id", "path", "data_store_id", "object_id"]
            }
        ),
        Tool(
            name="list_external_entry_ids",
            description="List external entry IDs associated with a data store",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID to query"
                    },
                    "limit": {
                        "type": "integer",
                        "description": "Max IDs to return"
                    },
                    "next_cursor": {
                        "type": "string",
                        "description": "Pagination cursor from previous response"
                    }
                },
                "required": ["filespace_id", "data_store_id"]
            }
        ),
        Tool(
            name="delete_external_entry",
            description="Delete an external entry from a filespace",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "entry_id": {
                        "type": "string",
                        "description": "External entry ID to delete"
                    },
                    "confirm": {
                        "type": "boolean",
                        "description": "Must be true to proceed"
                    }
                },
                "required": ["filespace_id", "entry_id", "confirm"]
            }
        ),

        # High-Level Workflow Tools
        Tool(
            name="ensure_folder_path",
            description="Create all directories in a filespace path, returning leaf entry ID.",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "path": {
                        "type": "string",
                        "description": "Directory path to create (e.g. /videos/2024/clips)"
                    }
                },
                "required": ["filespace_id", "path"]
            }
        ),
        Tool(
            name="import_s3_object",
            description="Ensure directory path exists, then link one S3 object as an external entry.",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID for the S3 bucket"
                    },
                    "s3_key": {
                        "type": "string",
                        "description": "S3 object key (e.g. media/clip.mp4)"
                    },
                    "ll_path": {
                        "type": "string",
                        "description": "Full filespace path for the entry (e.g. /media/clip.mp4)"
                    }
                },
                "required": ["filespace_id", "data_store_id", "s3_key", "ll_path"]
            }
        ),
        Tool(
            name="bulk_import_s3_objects",
            description="Ensure all directories exist, then link multiple S3 objects as external entries.",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Filespace ID"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Data store ID for the S3 bucket"
                    },
                    "objects": {
                        "type": "array",
                        "description": "List of objects to import",
                        "items": {
                            "type": "object",
                            "properties": {
                                "s3_key": {"type": "string", "description": "S3 object key"},
                                "ll_path": {"type": "string", "description": "Target filespace path"}
                            },
                            "required": ["s3_key", "ll_path"]
                        }
                    },
                    "stop_on_error": {
                        "type": "boolean",
                        "description": "Stop processing on first error (default false)"
                    }
                },
                "required": ["filespace_id", "data_store_id", "objects"]
            }
        ),
        Tool(
            name="get_connect_workflow_guide",
            description="Return step-by-step guide for the LucidLink Connect import workflow.",
            inputSchema={"type": "object", "properties": {}}
        ),
        Tool(
            name="generate_connect_ui",
            description="Generate a standalone HTML/JS app for S3 to LucidLink Connect imports.",
            inputSchema={
                "type": "object",
                "properties": {
                    "filespace_id": {
                        "type": "string",
                        "description": "Pre-fill filespace ID in the UI"
                    },
                    "data_store_id": {
                        "type": "string",
                        "description": "Pre-fill data store ID in the UI"
                    }
                }
            }
        ),

        # Auth
        Tool(
            name="initialize_api",
            description="Initialize the API client with a bearer token",
            inputSchema={
                "type": "object",
                "properties": {
                    "token": {
                        "type": "string",
                        "description": "Bearer token (uses stored token if omitted)"
                    }
                }
            }
        ),
    ]


# Tool Implementation
@server.call_tool()
async def call_tool(name: str, arguments: dict):
    """Execute tool based on name and arguments"""
    global api_client

    try:
        # Docker Management Tools
        if name == "check_docker_status":
            installed = docker_mgr.is_docker_installed()
            running = docker_mgr.is_docker_running() if installed else False
            status = {"installed": installed, "running": running, "container_status": "unknown"}
            if not installed:
                status["message"] = "Docker Desktop is not installed. Please install from https://docker.com/products/docker-desktop"
            elif not running:
                if docker_mgr.start_docker():
                    status["running"] = True
                    status["message"] = "Docker Desktop started successfully"
                else:
                    status["message"] = "Failed to start Docker Desktop. Please start it manually."
            else:
                container, error = docker_mgr.ensure_container_running()
                if container:
                    status["container_status"] = container.status
                    status["message"] = "Docker and API container are ready"
                else:
                    status["container_status"] = "not_ready"
                    status["message"] = error or "Docker is running but API container failed to start"
            return [TextContent(type="text", text=json.dumps(status, indent=2))]

        elif name == "start_api_container":
            container, error = docker_mgr.ensure_container_running()
            if container:
                return [TextContent(type="text", text=format_success_message(
                    "API Container Started",
                    {"container_id": container.short_id, "status": container.status}
                ))]
            else:
                return [TextContent(type="text", text=format_error_message(
                    "Start API Container",
                    error or "Failed to start container. Check Docker Desktop."
                ))]

        elif name == "stop_api_container":
            success = docker_mgr.stop_container()
            if success:
                return [TextContent(type="text", text=format_success_message(
                    "API Container Stopped", {"status": "Container stopped successfully"}
                ))]
            else:
                return [TextContent(type="text", text=format_error_message(
                    "Stop API Container",
                    "Failed to stop container. It may not be running or Docker Desktop may not be running."
                ))]

        elif name == "view_container_logs":
            lines = arguments.get("lines", 50)
            logs = docker_mgr.get_container_logs(lines)
            return [TextContent(type="text", text=f"📜 Last {lines} lines of container logs:\n\n{logs}")]

        elif name == "pull_container_image":
            success, message = docker_mgr.pull_image(CONTAINER_IMAGE)
            if success:
                return [TextContent(type="text", text=format_success_message(
                    "Container Image Pulled",
                    {"image": CONTAINER_IMAGE, "message": message, "next_step": "You can now start the API container"}
                ))]
            else:
                return [TextContent(type="text", text=format_error_message("Pull Container Image", message))]

        elif name == "check_container_image":
            if docker_mgr.image_exists(CONTAINER_IMAGE):
                return [TextContent(type="text", text=format_success_message(
                    "Container Image Status",
                    {"image": CONTAINER_IMAGE, "status": "Available locally", "message": "Container image is ready to use"}
                ))]
            else:
                return [TextContent(
                    type="text",
                    text=f"⚠️ Container image '{CONTAINER_IMAGE}' not found locally.\n\n"
                         f"The image will be automatically pulled from Docker Hub when you start the container.\n\n"
                         f"Or you can pull it now by saying: 'Pull the container image'"
                )]

        elif name == "initialize_api":
            token = arguments.get("token") or get_bearer_token()
            if not token:
                return [TextContent(type="text", text=format_error_message(
                    "Initialize API",
                    "No bearer token provided. Please set LUCIDLINK_BEARER_TOKEN environment variable or provide token."
                ))]
            api_client = LucidLinkAPIClient(token)
            health = api_client.get_service_health()
            if health.success:
                return [TextContent(type="text", text=format_success_message(
                    "API Initialized", {"status": "Connected", "endpoint": API_BASE_URL}
                ))]
            else:
                return [TextContent(type="text", text=format_error_message(
                    "Initialize API", f"Failed to connect: {health.error}"
                ))]

        # Ensure API client is initialized for remaining tools
        if not api_client:
            token = get_bearer_token()
            if not token:
                return [TextContent(
                    type="text",
                    text="⚠️ API not initialized. Please provide your bearer token first using the initialize_api tool."
                )]
            api_client = LucidLinkAPIClient(token)

        # Ensure Docker and container are running
        if not docker_mgr.is_docker_running():
            docker_mgr.start_docker()
        container, error = docker_mgr.ensure_container_running()
        if not container:
            return [TextContent(type="text", text=format_error_message(
                "Container Setup",
                error or "Failed to start API container. Please check Docker status."
            ))]

        # Filesystem Entry tools
        if name == "create_entry":
            response = api_client.create_entry(
                arguments["filespace_id"], arguments["parent_id"], arguments["name"])
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    f"Created directory '{arguments['name']}'", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Create Entry", response.error))]

        elif name == "resolve_entry":
            response = api_client.resolve_entry(arguments["filespace_id"], arguments["path"])
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    f"Resolved path '{arguments['path']}'", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Resolve Entry", response.error))]

        elif name == "get_entry":
            response = api_client.get_entry(arguments["filespace_id"], arguments["entry_id"])
            if response.success:
                return [TextContent(type="text", text=format_success_message("Entry Details", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Get Entry", response.error))]

        elif name == "delete_entry":
            if not arguments.get("confirm", False):
                return [TextContent(type="text", text="⚠️ Deletion not confirmed. Set confirm=true to proceed.")]
            response = api_client.delete_entry(arguments["filespace_id"], arguments["entry_id"])
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    "Deleted Entry", {"entry_id": arguments["entry_id"]}))]
            else:
                return [TextContent(type="text", text=format_error_message("Delete Entry", response.error))]

        elif name == "list_entry_children":
            response = api_client.list_entry_children(
                arguments["filespace_id"], arguments["entry_id"],
                limit=arguments.get("limit"), next_cursor=arguments.get("next_cursor"))
            if response.success:
                data = response.data if response.data else {}
                entries = data.get("data", {}).get("entries", []) if isinstance(data, dict) else []
                next_cur = data.get("data", {}).get("nextCursor") if isinstance(data, dict) else None
                if entries:
                    entry_list = "\n".join([
                        f"• [{e.get('type','?')}] {e.get('name','?')} (ID: {e.get('id','N/A')})"
                        for e in entries
                    ])
                    text = f"📂 {len(entries)} item(s):\n\n{entry_list}"
                    if next_cur:
                        text += f"\n\n🔄 More results available. Use next_cursor='{next_cur}' to continue."
                    return [TextContent(type="text", text=text)]
                else:
                    return [TextContent(type="text", text="📂 Directory is empty.")]
            else:
                return [TextContent(type="text", text=format_error_message("List Entry Children", response.error))]

        # External Data Store tools
        elif name == "create_data_store":
            response = api_client.create_data_store(
                filespace_id=arguments["filespace_id"],
                name=arguments["name"],
                access_key=arguments["access_key"],
                secret_key=arguments["secret_key"],
                bucket_name=arguments["bucket_name"],
                use_virtual_addressing=arguments["use_virtual_addressing"],
                region=arguments.get("region"),
                endpoint=arguments.get("endpoint"),
                url_expiration_minutes=arguments.get("url_expiration_minutes"),
            )
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    f"Created data store '{arguments['name']}'", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Create Data Store", response.error))]

        elif name == "list_data_stores":
            response = api_client.list_data_stores(
                arguments["filespace_id"], name=arguments.get("name"))
            if response.success:
                data = response.data if response.data else {}
                stores = data.get("data", []) if isinstance(data, dict) else []
                if stores:
                    store_list = "\n".join([
                        f"• {s.get('name','Unknown')} (ID: {s.get('id','N/A')}, kind: {s.get('kind','N/A')})"
                        for s in stores
                    ])
                    return [TextContent(type="text", text=f"🗄️ {len(stores)} data store(s):\n\n{store_list}")]
                else:
                    return [TextContent(type="text", text="🗄️ No data stores found for this filespace.")]
            else:
                return [TextContent(type="text", text=format_error_message("List Data Stores", response.error))]

        elif name == "get_data_store":
            response = api_client.get_data_store(arguments["filespace_id"], arguments["data_store_id"])
            if response.success:
                return [TextContent(type="text", text=format_success_message("Data Store Details", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Get Data Store", response.error))]

        elif name == "update_data_store":
            response = api_client.update_data_store(
                arguments["filespace_id"], arguments["data_store_id"],
                arguments["access_key"], arguments["secret_key"])
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    "Updated Data Store Credentials", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Update Data Store", response.error))]

        elif name == "delete_data_store":
            if not arguments.get("confirm", False):
                return [TextContent(type="text", text="⚠️ Deletion not confirmed. Set confirm=true to proceed.")]
            response = api_client.delete_data_store(arguments["filespace_id"], arguments["data_store_id"])
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    "Deleted Data Store", {"data_store_id": arguments["data_store_id"]}))]
            else:
                return [TextContent(type="text", text=format_error_message("Delete Data Store", response.error))]

        # External Entry tools
        elif name == "create_external_entry":
            response = api_client.create_external_entry(
                filespace_id=arguments["filespace_id"],
                path=arguments["path"],
                data_store_id=arguments["data_store_id"],
                object_id=arguments["object_id"],
            )
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    f"Created external entry at '{arguments['path']}'", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Create External Entry", response.error))]

        elif name == "list_external_entry_ids":
            response = api_client.list_external_entry_ids(
                arguments["filespace_id"], arguments["data_store_id"],
                limit=arguments.get("limit"), next_cursor=arguments.get("next_cursor"))
            if response.success:
                data = response.data if response.data else {}
                ids = data.get("data", {}).get("ids", []) if isinstance(data, dict) else []
                next_cur = data.get("data", {}).get("nextCursor") if isinstance(data, dict) else None
                text = f"🔗 {len(ids)} external entry ID(s):\n\n" + "\n".join(f"• {eid}" for eid in ids)
                if next_cur:
                    text += f"\n\n🔄 More available. Use next_cursor='{next_cur}' to continue."
                return [TextContent(type="text", text=text if ids else "🔗 No external entries found.")]
            else:
                return [TextContent(type="text", text=format_error_message("List External Entry IDs", response.error))]

        elif name == "delete_external_entry":
            if not arguments.get("confirm", False):
                return [TextContent(type="text", text="⚠️ Deletion not confirmed. Set confirm=true to proceed.")]
            response = api_client.delete_external_entry(arguments["filespace_id"], arguments["entry_id"])
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    "Deleted External Entry", {"entry_id": arguments["entry_id"]}))]
            else:
                return [TextContent(type="text", text=format_error_message("Delete External Entry", response.error))]

        # High-Level Workflow Tools
        elif name == "ensure_folder_path":
            filespace_id = arguments["filespace_id"]
            path = arguments["path"]
            success, leaf_id, error = api_client.ensure_folder_path(filespace_id, path)
            if success:
                return [TextContent(type="text", text=format_success_message(
                    f"Ensured folder path '{path}'",
                    {"path": path, "leaf_entry_id": leaf_id}
                ))]
            else:
                return [TextContent(type="text", text=format_error_message("Ensure Folder Path", error))]

        elif name == "import_s3_object":
            filespace_id = arguments["filespace_id"]
            data_store_id = arguments["data_store_id"]
            s3_key = arguments["s3_key"]
            ll_path = arguments["ll_path"]
            # Ensure parent directory exists
            path_parts = ll_path.strip("/").split("/")
            dir_path = "/" + "/".join(path_parts[:-1]) if len(path_parts) > 1 else ""
            if dir_path and dir_path != "/":
                success, _, error = api_client.ensure_folder_path(filespace_id, dir_path)
                if not success:
                    return [TextContent(type="text", text=format_error_message(
                        "Import S3 Object", f"Failed to create directory '{dir_path}': {error}"))]
            response = api_client.create_external_entry(filespace_id, ll_path, data_store_id, s3_key)
            if response.success:
                return [TextContent(type="text", text=format_success_message(
                    f"Imported S3 object '{s3_key}' → '{ll_path}'", response.data))]
            else:
                return [TextContent(type="text", text=format_error_message("Import S3 Object", response.error))]

        elif name == "bulk_import_s3_objects":
            filespace_id = arguments["filespace_id"]
            data_store_id = arguments["data_store_id"]
            objects = arguments["objects"]
            stop_on_error = arguments.get("stop_on_error", False)
            # Collect unique directories
            dirs = set()
            for obj in objects:
                ll_path = obj["ll_path"]
                parts = ll_path.strip("/").split("/")
                if len(parts) > 1:
                    dirs.add("/" + "/".join(parts[:-1]))
            # Ensure directories (sorted so parents before children)
            dir_failures = []
            for dir_path in sorted(dirs):
                success, _, error = api_client.ensure_folder_path(filespace_id, dir_path)
                if not success:
                    dir_failures.append({"dir": dir_path, "error": error})
                    if stop_on_error:
                        return [TextContent(type="text", text=format_error_message(
                            "Bulk Import", f"Directory creation failed for '{dir_path}': {error}"))]
            # Link each object
            succeeded, failed, failures = 0, 0, []
            for obj in objects:
                s3_key = obj["s3_key"]
                ll_path = obj["ll_path"]
                response = api_client.create_external_entry(filespace_id, ll_path, data_store_id, s3_key)
                if response.success:
                    succeeded += 1
                else:
                    failed += 1
                    failures.append({"s3_key": s3_key, "ll_path": ll_path, "error": response.error})
                    if stop_on_error:
                        break
            summary = {
                "total": len(objects),
                "succeeded": succeeded,
                "failed": failed,
                "dir_failures": dir_failures,
                "object_failures": failures
            }
            if failed == 0 and not dir_failures:
                return [TextContent(type="text", text=format_success_message(
                    f"Bulk Import: {succeeded}/{len(objects)} objects imported", summary))]
            else:
                msg = f"Bulk Import completed with errors: {succeeded} succeeded, {failed} failed"
                return [TextContent(type="text", text=f"⚠️ {msg}\n\n{json.dumps(summary, indent=2)}")]

        elif name == "get_connect_workflow_guide":
            return [TextContent(type="text", text=CONNECT_WORKFLOW_GUIDE)]

        elif name == "generate_connect_ui":
            filespace_id = arguments.get("filespace_id", "")
            data_store_id = arguments.get("data_store_id", "")
            html = CONNECT_UI_TEMPLATE.replace("{FILESPACE_ID}", filespace_id).replace("{DATA_STORE_ID}", data_store_id)
            return [TextContent(type="text", text=html)]

        else:
            return [TextContent(type="text", text=f"❌ Unknown tool: {name}")]

    except Exception as e:
        logger.error(f"Tool execution error: {e}", exc_info=True)
        return [TextContent(
            type="text",
            text=f"❌ Unexpected error: {str(e)}\n\nPlease check the logs for more details."
        )]


# Resources
@server.list_resources()
async def list_resources():
    return [
        Resource(
            uri="lucidlink://connect-help",
            name="LucidLink Connect Help",
            mimeType="text/plain",
            description="Help documentation for LucidLink Connect MCP server"
        )
    ]


@server.read_resource()
async def read_resource(uri: str):
    if uri == "lucidlink://connect-help":
        return [TextContent(type="text", text=CONNECT_WORKFLOW_GUIDE)]
    return []


# Main entry point
async def main():
    """Main entry point for the Connect MCP server"""
    token = get_bearer_token()
    if not token:
        logger.warning("No bearer token found. User will need to provide one.")
    logger.info("Starting LucidLink Connect MCP Server...")
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            server.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())
